
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://yquujzqftouofrkmzcep.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InlxdXVqenFmdG91b2Zya216Y2VwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDMzNjQ4ODUsImV4cCI6MjA1ODk0MDg4NX0.2pjqC5wXPlj1jO2QzG58D5EpjF-JqV-RXjttVe8dj04";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});
